version: "3"

services:
  db:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_DATABASE=workshop
      - MYSQL_USER=workshop
      - MYSQL_PASSWORD=workshop
      - MYSQL_ROOT_PASSWORD=workshop
    ports:
      - "33067:3306"
    volumes:
      - db_volume:/var/lib/mysql

  backend:
    image: strapi/strapi
    working_dir: /srv/backend
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=workshop
      - DATABASE_USERNAME=workshop
      - DATABASE_PASSWORD=workshop
      - DATABASE_SSL=false
      - PORT=1337
      - ADMIN_JWT_SECRET=mIMPgb1sknbKqPZNqv75axfGuYgd3uUmmXYybXw3L8a2bmRKzPIPZsWYsYqrXgiHse7wUH30Pj9B9B+ko35mB+/3YXUX6MPdTojtwqiD9oUgbYXkK2fl5GGTEG7EznotxRFJd0Q3euwrYPwDCzVsUj5Sh5WWZagM6yTBkV6G/CdeutPREPP/R66C8zNSA2IE3H2xxo/fzRwiw3RNcoTG3i7iz7ydg5hv6gHRyw8+8T+EDUw6UMLIxt6oStO/xXPvSpwv5l3I/MfmLeIoNV7pTRhd3rW1jKaoYWfjzQurdDuIsR1CeYTcfiDaGWzDZPe+4EMPTmfTdYWjhJFIXvZ+Fg==
    volumes:
      - ./backend:/srv/backend:rw
    ports:
      - "1337:1337"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ../vue-cli/Dockerfile
    user: node
    working_dir: /srv/frontend
    environment:
      - VUE_APP_BASE_URL=http://localhost:1337
    volumes:
      - ./frontend:/srv/frontend
    ports:
      - "8080:8080"

volumes:
  db_volume:
    driver: local
